### ISSUE TITLE
Hi Can you share a Flyme 6 Build ?

### ISSUE THREAD

**Issue by Bauuuuu** [JDKCHINA/Flyme6_base_NX512J#1]

**Comment by JDKCHINA** [comment]
FlymeOS Project in github.You can should Readme.

**Comment by Bauuuuu** [comment]
dont you have prebuilt rom?

**Comment by JDKCHINA** [comment]
This is a project.nihave learn it,READme is easy.

**Comment by Bauuuuu** [comment]
no time to work on it. Someone asked me about so i though i will ask you. If you dont have flyme build thats fine.

**Comment by JDKCHINA** [comment]
http://github.com/FlymeOS/manifest

**Comment by JDKCHINA** [comment]
you can read README.md .
flyme config
flyme project
flyme patchall this reject you have slove reject.
flyme fullota

**Comment by JDKCHINA** [comment]
This project have aosp and LineaOS.
